services:
  - type: web
    name: wonderly-rcs-review-demo
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_API_KEY
        sync: false
      - key: TWILIO_API_SECRET
        sync: false
      - key: TWILIO_MESSAGING_SERVICE_SID
        sync: false
